### ISSUE TITLE
请问我使用后新增的子页面的标签页高度固定死了只有很小一块怎么解决？

### ISSUE THREAD

**Issue by zengsiyong** [lianruanjian/bootstrap-closable-tab#6]
![image](https://user-images.githubusercontent.com/27494295/34291472-581dc076-e737-11e7-8915-2006f33b5374.png)
我画框框的地方是还有数据的，但是我现在浏览器中智能用滚轮才能显示后面的内容，请问是要怎么修改样式？

**Comment by zyqwst** [comment]
不知道你用的div方式还是iframe方式。如果是div方式的话，高度是你的加入的标签页高度决定的；

		  <ul class="nav nav-tabs" role="tablist">
		  </ul>
		  <div class="tab-content" style="width:100%;">
		  </div>
		  
.tab-content这个div会自动撑开
