### ISSUE TITLE
div方式无法正常加载网页?

### ISSUE THREAD

**Issue by iSwfe** [lianruanjian/bootstrap-closable-tab#7]
当使用div方式时,网页无法加载出来,这是我的设置:
```
<script type="text/javascript">
	var defaultTab={
		id: 'welcome',
		name: 'Welcome!',
		url: 'http://www.baidu.com',
		closable: false
	};

	$(closableTab.addTab(defaultTab));
</script>
```

然后新增选项卡后,一直显示`正在加载...`.
<img width="631" alt="2018-01-07 17 41 25" src="https://user-images.githubusercontent.com/20889699/34648316-d8eb3a1a-f3d2-11e7-88e7-575bff26e4e1.png">

**Comment by zyqwst** [comment]
你看看控制台，肯定有禁止跨域的错误！

**Comment by iSwfe** [comment]
明白了,我对JS学的还不够,还在琢磨中.
