### ISSUE TITLE
删除元素后无法创建同个id元素的问题

### ISSUE THREAD

**Issue by jingliancui** [lianruanjian/bootstrap-closable-tab#8]
重现:
1.新建一个id为1的tab,
2.关闭这个tab
3.新建一个id为1的tab

结果:无法创建

解决方法:
源码内于底部这两行后面追加代码:
$("#" + val1).remove();
$("#" + containerId).remove();

追加内容:
document.getElementById(val1).removeAttribute("id");
document.getElementById(containerId).removeAttribute("id")

**Comment by zyqwst** [comment]
谢谢，当时做来玩的，有点仓促。
